language: node_js
node_js: 
  - "4.1"
before_install:
  - npm config set ca ""
install:
  - npm install -g grunt-cli
  - npm install
after_success: 
  - npm run-script coverage-lcov
  - npm run-script coveralls